version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - sqlite_data:/app/backend/instance

volumes:
  sqlite_data:
